name: Myna Project
description: 
  
url: "http://myna-project-test.github.io"

paginate: 10

markdown: rdiscount

# translation tags
t:
  ita:
    home:  "Home"
    about: "About"
    developer : "Sviluppatori"
    documentation : "Documentazione"
    demo : "Demo online"
    use : "Usa online"
    contact : "Contatti"
    language : "Lingua"
    gateway-description : "Descrizione gateway"
    operation: "Funzionamento"
    installation : "Installazione"
    data-history : "Storico dati"
    logging : "Logging"
    configuration-file-format : "Formato file di configurazione"
    daemon : "Daemon"
    device : "Device"
    holding-registers : "Struttura degli Holding Registers"
    input-registers : "Struttura degli Input Registers"
    coils: "Struttura delle coils"
    config-myna: "Struttura ed esempio file di configurazione di Myna"
    back_to_top : "Torna su"
  eng:
    home:  "Home"
    about: "About"
    developer : "Developer"
    documentation : "Documentation"
    demo : "Online demo"
    use : "Online use"
    contact : "Contact"
    language : "Language"
    gateway-description : "Gateway description"
    operation: "Operation"
    installation : "Installation"
    data-history : "Data history"
    logging : "Logging"
    configuration-file-format : "Configuration file format"
    daemon : "Daemon"
    device : "Device"
    holding-registers : "Holding register structure"
    input-registers : "Input Registers structure"
    coils: "Coils structure"
    config-myna: "Example of Myna configuration file"
    back_to_top : "Back to top"